version: '3.9'
services:
  miner_superseis:
    env_file: .env
    build: ./src/miners/superseis
    volumes:
      - ./src/miners/superseis:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  miner_stock:
    env_file: .env
    build: ./src/miners/stock
    volumes:
      - ./src/miners/stock:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  miner_fortis:
    env_file: .env
    build: ./src/miners/fortis
    volumes:
      - ./src/miners/fortis:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  miner_gg:
    env_file: .env
    build: ./src/miners/gg
    volumes:
      - ./src/miners/gg:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  miner_biggie:
    env_file: .env
    build: ./src/miners/biggie
    volumes:
      - ./src/miners/biggie:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  miner_arete:
    env_file: .env
    build: ./src/miners/arete
    volumes:
      - ./src/miners/arete:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  miner_casarica:
    env_file: .env
    build: ./src/miners/casarica
    volumes:
      - ./src/miners/casarica:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  miner_tupi:
    env_file: .env
    build: ./src/miners/tupi
    volumes:
      - ./src/miners/tupi:/app
    networks:
      - miner-app
    depends_on:
      - mongo
    command: bash -c "while ! curl -s http://api:8080/; do sleep 5; done; python3 -u main.py"
  api:
    build:
      context: ./src/api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - miner-app
    depends_on:
      - mongo
    command: ./main
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    networks:
      - miner-app
    volumes:
      - mongo-data:/data/db
      - ./src/mongo-data/init.js:/docker-entrypoint-initdb.d/init.js

networks:
  miner-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local