version: '3.9'
services:
  # miner_superseis:
  #   env_file: .env
  #   build: ./src/miners/superseis
  #   volumes:
  #     - ./src/miners/superseis:/app
  #   networks:
  #     - miner-app
  #   depends_on:
  #     - db
  #   command: bash -c "while !</dev/tcp/db/27017; do sleep 5; done; python3 -u main.py" # This is to wait for the db to be ready before starting the miner
  miner_biggie:
    env_file: .env
    build: ./src/miners/biggie
    volumes:
      - ./src/miners/biggie:/app
    networks:
      - miner-app
    depends_on:
      - db
    command: bash -c "while !</dev/tcp/db/27017; do sleep 5; done; python3 -u main.py" # This is to wait for the db to be ready before starting the miner
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file:
      - .env
    networks:
      - miner-app
    volumes:
      - ./db/mongo/:/data/db

networks:
  miner-app:
    driver: bridge

volumes:
  db:
    driver: local