version: '3.9'
services:
  miner_superseis:
    env_file: .env
    build: ./src/miners/osm
    volumes:
      - ./src/miners/osm:/app
    depends_on:
      - db
    command: bash -c "while !</dev/tcp/db/5432; do sleep 5; done; python3 -u main.py" # This is to wait for the db to be ready before starting the miner
  miner_biggie:
    env_file: .env
    build: ./src/miners/osm
    volumes:
      - ./src/miners/osm:/app
    depends_on:
      - db
    command: bash -c "while !</dev/tcp/db/5432; do sleep 5; done; python3 -u main.py" # This is to wait for the db to be ready before starting the miner
  db:
    image: mongo:latest
    env_file: .env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/db:/docker-entrypoint-initdb.d

volumes:
  db: