version: '3.9'
services:
  # miner_biggie:
  #   env_file: .env
  #   build: ./src/miners/biggie
  #   volumes:
  #     - ./src/miners/biggie:/app
  #   networks:
  #     - miner-app
  #   depends_on:
  #     - mongo
  #   command: bash -c "while !</dev/tcp/mongo/27017; do sleep 5; done; python3 -u main.py" # This is to wait for the db to be ready before starting the miner
  api:
    build:
      context: ./src/api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - miner-app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    networks:
      - miner-app
    volumes:
      - mongo-data:/data/db
      - ./src/mongo-data/init.js:/docker-entrypoint-initdb.d/init.js

networks:
  miner-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local