# Use the official Golang image
FROM golang:1.20

# Set the working directory inside the container
WORKDIR /app

RUN go mod init github.com/NicholasHellmers/Paraguayan-Products-Miner

# Copy the Go module files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the application code
COPY . .

# Build the Go application
RUN go build -o main .

# Expose the application's port
EXPOSE 8080

# Run the application
CMD ["./main"]
